[package]
name = "dodgeball-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { workspace = true }
bevy_flycam = "0.11.0"
bevy_infinite_grid = "0.9.0"
